language: android

env:
  global:
    - ADB_INSTALL_TIMEOUT=30
# Using the new Container-Based Infrastructure
    - sudo: false
# Turning off caching to avoid caching Issues
    - cache: false
# Initiating clean Gradle output
    - TERM=dumb
# Giving even more memory to Gradle JVM
    - GRADLE_OPTS="-Xmx2048m -XX:MaxPermSize=1024m"

android:
  components:
    - tools
    - build-tools-23.0.3
    - extra-android-m2repository
    - android-23
    - android-19
    
 env:
  matrix:
    - ANDROID_TARGET=android-19 ANDROID_ABI=armeabi-v7a
    - ANDROID_TARGET=android-23 ANDROID_ABI=armeabi-v7a   

# Emulator Management: Create, Start and Wait
before_script:
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script: ./gradlew connectedAndroidTest
